  - name: Run iTrust build job.
    become: yes
    uri:
      url: "{{ jenkins_url }}/job/{{jenkinitrustjobname}}/build"
      method: GET
      # user: admin
      # password: admin
      # force_basic_auth: yes
      status_code: 201

  - name: Run checkbox build job.
    become: yes
    uri:
      url: "{{ jenkins_url }}/job/{{jenkincheckboxjobname}}/build"
      method: GET
      status_code: 201
