---
 - import_tasks: setUserAndGroups.yml
 - name: Installing Git - Maven
   apt:
     name: maven
     state: present
     update_cache: yes

 - name: Downloading Jenkins CLI Jar
   get_url:
     url: "{{jenkins_url}}/jnlpJars/jenkins-cli.jar"
     dest: "{{home_path}}/"
     mode: 0755

 - name: Restarting Jenkins
   service:
     name: jenkins
     state: restarted
##  when: jenkins_install.changed

 - name: "Wait For Jenkins To Come Up"
   uri:
     url: "{{jenkins_url}}"
     status_code: 200
   register: result
   until: >
    'status' in result and
    result['status'] == 200
   retries: 10
   delay: 15
##  when: jenkins_install.changed

# - name: Install Jenkin Plugins
#   jenkins_plugin:
#     name: "{{ item }}"
#     url_username: "{{ jenkins_user }}"
#     url_password: "{{ jenkins_password }}"
#     url: "{{ jenkins_url }}"
#     validate_certs: no
#   with_items:
#     - maven-plugin

 - name: Install/update plugins
   sudo: yes
   action: command java -jar {{ home_path }}/jenkins-cli.jar -s {{ jenkins_url }} install-plugin {{ item }}
   with_items:
     - maven-plugin
     - github
     - jacoco
     - junit
     - test-stability
     - postbuildscript
     - build-timeout
   register: jenkins_plugins
#  when: plugins_installed.changed and plugins_installed.stdout.find('{{ item }}') == -1

 - name: Install jenkins-job-builder
   apt:
     name: jenkins-job-builder
     state: present
     force: yes
     #update_cache: yes
     #cache_valid_time: 1800
   become: yes

 - name: Setting number of executors to 1
   become: true
   command: "sed -ie 's#<numExecutors>[^<][^<]*</numExecutors>#<numExecutors>1</numExecutors>#' {{jenkins_path}}/config.xml"

 - name: Restarting Jenkins
   service:
     name: jenkins
     state: restarted
   when: jenkins_plugins.changed

 - name: "Wait For Jenkins To get Up"
   uri:
     url: "{{jenkins_url}}/cli/"
     status_code: 200
   register: result
   until: >
    'status' in result and
    result['status'] == 200
   retries: 10
   delay: 10
   when: jenkins_plugins.changed

 - name: Checking Jenkins State
   service:
     name: jenkins
     state: started
